auth_enabled: false
common:
  path_prefix: /data/loki
  replication_factor: 1
server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    dir: /data/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s

limits_config:
  allow_structured_metadata: false
  volume_enabled: true
schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb-index
    cache_location: /data/loki/tsdb-cache
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /data/loki/compactor

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 16
